= In-graph tree indexing

Storing tree structures in a graph database makes a lot of sense. However, some trees are easier to play with than others.
Some constraints will make things much more complicated. Ordered children for instance, or time-dependent hierarchies (a tree 
that changes in time), or ordered time-dependent hierarchies...

In this GraphGist, I will present an indexing structure that makes it easier to deal with that kind of trees and that allows:

* Returning the full hierarchy with a single query, in a depth-first traversal fashion that allows building back the 
hierarchy in memory using your client language.
* Similarly, extracting the full subtree from a given node, with a single query.
* List direct children of any given node within the tree.

All of this for arbitrary depths of trees and with preservation of children order at each level in the returned data!

_NB: As you will see this technique trades storage space for query efficiency, so it may not be appropriate for large
amounts of data._

== Let's start with a tree

Here's the tree we'll be working with:

//hide
//setup
[source,cypher]
----
CREATE (root:CATEGORIES {name: '1. Motorcycle Racing Categories'})

CREATE (root)-[:HAS]->(road:CATEGORY {name: '1.1 Road Racing'})
CREATE (road)-[:HAS]->(gp:SUBCATEGORY {name: '1.1.1 Grand Prix'})
CREATE (gp)-[:HAS]->(moto3:CLASS {name: '1.1.1.1 Moto3'})
CREATE (gp)-[:HAS]->(moto2:CLASS {name: '1.1.1.2 Moto2'})
CREATE (gp)-[:HAS]->(motogp:CLASS {name: '1.1.1.3 MotoGP'})

CREATE (road)-[:HAS]->(sbk:SUBCATEGORY {name: '1.1.2 Superbike'})
CREATE (road)-[:HAS]->(ssp:SUBCATEGORY {name: '1.1.3 Supersport'})
CREATE (road)-[:HAS]->(endurance:SUBCATEGORY {name: '1.1.4 Endurance'})
CREATE (road)-[:HAS]->(sidecar:SUBCATEGORY {name: '1.1.5 Sidecar'})
CREATE (road)-[:HAS]->(tradi:SUBCATEGORY {name: '1.1.6 Traditional'})

CREATE (root)-[:HAS]->(cross:CATEGORY {name: '1.2 Motocross'})
CREATE (cross)-[:HAS]->(supercross:SUBCATEGORY {name: '1.2.1 Supercross'})
CREATE (cross)-[:HAS]->(supermoto:SUBCATEGORY {name: '1.2.2 Supermoto'})

RETURN *
----

// graph

As you can see, this tree is ordered. If we wanted to display the complete hierarchy of motorcycle racing categories as a plan
for an article (just as it's done in http://en.wikipedia.org/wiki/Motorcycle_racing#Motorcycle_Grand_Prix[this wikipedia article] the data's been taken from), we'd probably love to query the whole tree and have nothing more to do than display it, confident that items will be in correct order.


